#include <iostream>
#include <thread>
#include <algorithm>
#include "ui/ui.h" // generated by EEZ Studio
#include "lvgl/lvgl.h"
#include "mod.hpp"
#include "looper.hpp"
#include "sequencer.hpp"
#include "tuner.hpp"
#include "player.hpp"

// #include "rx/rx.hpp"
#include "transport/zmq_transport.hpp"
#include "protocol/protocol.hpp"
#include <nlohmann/json.hpp>

ZmqTransport transport;

void init_ui()
{
    lv_init();

#if LV_USE_LINUX_DRM
    const char *device = "/dev/dri/card1";
    lv_display_t *disp = lv_linux_drm_create();
    if (disp == NULL)
    {
        return;
    }
    lv_linux_drm_set_file(disp, device, -1);
#endif

#if LV_USE_EVDEV
    const char *input_device = "/dev/input/event0";
    lv_indev_t *indev = lv_evdev_create(LV_INDEV_TYPE_POINTER, input_device);
    if (indev == NULL)
    {
        return;
    }
    lv_indev_set_display(indev, disp);
#endif

#if LV_USE_SDL
    lv_display_t *disp = lv_sdl_window_create(1024, 600);

    if (disp == NULL)
    {
        return;
    }
    lv_indev_t *mouse = lv_sdl_mouse_create();
    lv_indev_t *mousewheel = lv_sdl_mousewheel_create();
    lv_indev_t *kb = lv_sdl_keyboard_create();
#endif

    // init eez
    ui_init();
}

void on_event_tuner(EventTuner e){
    tuner_update(e.note, e.cents);
}

template <class... Ts>
struct Overloaded : Ts...
{
    using Ts::operator()...;
};

template <class... Ts>
Overloaded(Ts...) -> Overloaded<Ts...>;

const auto events_handlers = Overloaded{
    [](const EventLoopCount &m)
    { looper_set_loops_count(m); },
    [](const EventLoopPos &m)
    { looper_set_loop_pos(m.id, m.pos); },
    [](const EventLoopState &m)
    { looper_set_loop_state(m.id, m.state); },
    [](const EventLoopLen &m)
    { looper_set_loop_len(m.id, m.len); },
    [](const EventLoopList &m)
    { looper_set_loop_list(m); },
    [](const EventLoopSelected &m)
    { looper_set_loop_selected(m); },
    [](const EventPedalboardsList &m)
    { mod_set_pedalboard_list(m); },
    [](const EventPedalboardChanged &m)
    { mod_set_current_pedalboard(m); },
    [](const EventEffectParamChanged &m)
    { mod_set_plugin_parameter(m); },
    [](const EventPedalboardSnapshotChanged &m)
    { mod_set_current_snapshot(m); },
    [](const EventSequencerMidiFilesList &m)
    { sequencer_set_file_list(m); },
    [](const EventSequencerPosition &m)
    { sequencer_set_position(m); },
    [](const EventTuner &m)
    { on_event_tuner(m); },
    [](const EventRecorderFileList &m)
    { player_set_file_list(m); },
    [](const EventRecorderPlaying &m)
    { player_set_playing(m); },
    [](const EventRecorderRecording&m)
    { player_set_recording(m); },
    [](const EventRecorderStopped &m)
    { player_set_stopped(m); }
};

void readEvents(lv_timer_t *timer)
{
    /*Use the user_data*/
    ThreadSafeQueue<Event> *queue = static_cast<ThreadSafeQueue<Event> *>(
        lv_timer_get_user_data(timer));

    Event msg;
    while (queue->try_pop(msg))
    {
        std::visit(events_handlers, msg);
    }
}

int main(int argc, char **argv)
{
    init_ui();

    lv_timer_create(readEvents, 10, &transport.eventsQueue);
    // looper callbacks
    lv_obj_add_event_cb(objects.loop_add_button, add_loop_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(objects.loop_remove_button, remove_loop_clicked, LV_EVENT_CLICKED, NULL);

    // pedalboard callbacks
    lv_obj_add_event_cb(objects.pedalboards, pedalboard_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(objects.snapshots, pedalboard_snapshot_changed, LV_EVENT_VALUE_CHANGED, NULL);

    //sequencer callbacks
    lv_obj_add_event_cb(objects.sequencer_midi_files_list, midi_file_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(objects.sequencer_slider_bpm, bpm_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(objects.sequencer_slider_volume, volume_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(objects.sequencer_mute_button, sequencer_mute_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(objects.sequencer_state_button, sequencer_state_changed, LV_EVENT_VALUE_CHANGED, NULL);

    //player callbacks
    lv_obj_add_event_cb(objects.player_record_button, player_record_changed, LV_EVENT_VALUE_CHANGED, NULL);

    //tuner callbacks
    lv_obj_add_event_cb(objects.tuner_state, tuner_state, LV_EVENT_VALUE_CHANGED, NULL);

    transport.sendCommand(CmdListLoops{});
    transport.sendCommand(CmdListPedalboards{});
    transport.sendCommand(CmdSequencerListMidiFiles{});

    uint32_t sleep_ms;
    while (true)
    {
        uint32_t sleep_ms = lv_timer_handler();
        lv_sleep_ms(sleep_ms);
    }
}