#include <iostream>
#include <thread>
#include <algorithm>
#include "ui/ui.h" // generated by EEZ Studio
#include "lvgl/lvgl.h"
#include "mod.hpp"
#include "looper.hpp"
#include "sequencer.hpp"
#include "tuner.hpp"
#include "player.hpp"

// #include "rx/rx.hpp"
#include "transport/zmq_transport.hpp"
#include "protocol/protocol.hpp"
#include <nlohmann/json.hpp>

ZmqTransport transport;

void init_ui()
{
    lv_init();

#if LV_USE_LINUX_DRM
    const char *device = "/dev/dri/card1";
    lv_display_t *disp = lv_linux_drm_create();
    if (disp == NULL)
    {
        return;
    }
    lv_linux_drm_set_file(disp, device, -1);
#endif

#if LV_USE_EVDEV
    const char *input_device = "/dev/input/event0";
    lv_indev_t *indev = lv_evdev_create(LV_INDEV_TYPE_POINTER, input_device);
    if (indev == NULL)
    {
        return;
    }
    lv_indev_set_display(indev, disp);
#endif

#if LV_USE_SDL
    lv_display_t *disp = lv_sdl_window_create(1024, 600);

    if (disp == NULL)
    {
        return;
    }
    lv_indev_t *mouse = lv_sdl_mouse_create();
    lv_indev_t *mousewheel = lv_sdl_mousewheel_create();
    lv_indev_t *kb = lv_sdl_keyboard_create();
#endif

    // init eez
    ui_init();
}


/**
 * Events handlers
 */
void on_event_loop_count(EventLoopCount m)
{
    set_loops_count(m.count);
}

void on_event_loop_pos(EventLoopPos m)
{
    set_loop_pos(m.id, m.pos);
}

void on_event_loop_len(EventLoopLen m)
{
    set_loop_len(m.id, m.len);
}

void on_event_loop_state(EventLoopState m)
{
    set_loop_state(m.id, m.state);
}

void on_event_loop_list(EventLoopList m){
    set_loop_list(m.loops);
}

void on_event_loop_selected(EventLoopSelected m)
{
    set_loop_selected(int(m.id));
}

void on_event_pedalboards_list(EventPedalboardsList m)
{
    for (auto pedal : m.pedalboards)
    {
        lv_dropdown_add_option(objects.pedalboards, pedal.c_str(), LV_DROPDOWN_POS_LAST);
    }
}

void on_event_pedalboard_changed(EventPedalboardChanged m)
{
    set_current_pedalboard(m.pedalboard);
}

void on_event_effect_param_changed(EventEffectParamChanged e)
{
    update_plugin_parameter(e.instance_id, e.symbol, e.value);
}

void on_event_pedalboard_snapshot_changed(EventPedalboardSnapshotChanged e)
{
    set_current_snapshot(e.index);
}

void on_event_sequencer_midi_files_list(EventSequencerMidiFilesList e){
    lv_dropdown_clear_options(objects.sequencer_midi_files_list);
    for(auto midi: e.midiFiles){
        lv_dropdown_add_option(objects.sequencer_midi_files_list, midi.c_str(), LV_DROPDOWN_POS_LAST);
    }
}

void on_event_sequencer_position(EventSequencerPosition e){
    if(objects.sequencer_bar != nullptr){
        lv_bar_set_value(objects.sequencer_bar, (int)(e.pos * 10.0), LV_ANIM_OFF);
    }
}

void on_event_tuner(EventTuner e){
    tuner_update(e.note, e.cents);
}

void on_event_recorded_file_list(EventRecordedFileList e){
    player_set_file_list(e.files);
}

/***/

template <class... Ts>
struct Overloaded : Ts...
{
    using Ts::operator()...;
};

template <class... Ts>
Overloaded(Ts...) -> Overloaded<Ts...>;

const auto events_handlers = Overloaded{
    [](const EventLoopCount &m)
    { on_event_loop_count(m); },
    [](const EventLoopPos &m)
    { on_event_loop_pos(m); },
    [](const EventLoopState &m)
    { on_event_loop_state(m); },
    [](const EventLoopLen &m)
    { on_event_loop_len(m); },
    [](const EventLoopList &m)
    { on_event_loop_list(m); },
    [](const EventLoopSelected &m)
    { on_event_loop_selected(m); },
    [](const EventPedalboardsList &m)
    { on_event_pedalboards_list(m); },
    [](const EventPedalboardChanged &m)
    { on_event_pedalboard_changed(m); },
    [](const EventEffectParamChanged &m)
    { on_event_effect_param_changed(m); },
    [](const EventPedalboardSnapshotChanged &m)
    { on_event_pedalboard_snapshot_changed(m); },
    [](const EventSequencerMidiFilesList &m)
    { on_event_sequencer_midi_files_list(m); },
    [](const EventSequencerPosition &m)
    { on_event_sequencer_position(m); },
    [](const EventTuner &m)
    { on_event_tuner(m); },
    [](const EventRecordedFileList &m)
    { on_event_recorded_file_list(m); }
};

void readEvents(lv_timer_t *timer)
{
    /*Use the user_data*/
    ThreadSafeQueue<Event> *queue = static_cast<ThreadSafeQueue<Event> *>(
        lv_timer_get_user_data(timer));

    Event msg;
    while (queue->try_pop(msg))
    {
        std::visit(events_handlers, msg);
    }
}

int main(int argc, char **argv)
{
    init_ui();

    lv_timer_create(readEvents, 10, &transport.eventsQueue);
    // looper callbacks
    lv_obj_add_event_cb(objects.loop_add_button, add_loop_clicked, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(objects.loop_remove_button, remove_loop_clicked, LV_EVENT_CLICKED, NULL);

    // pedalboard callbacks
    lv_obj_add_event_cb(objects.pedalboards, pedalboard_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(objects.snapshots, pedalboard_snapshot_changed, LV_EVENT_VALUE_CHANGED, NULL);

    //sequencer callbacks
    lv_obj_add_event_cb(objects.sequencer_midi_files_list, midi_file_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(objects.sequencer_slider_bpm, bpm_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(objects.sequencer_slider_volume, volume_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(objects.sequencer_mute_button, sequencer_mute_changed, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(objects.sequencer_state_button, sequencer_state_changed, LV_EVENT_VALUE_CHANGED, NULL);

    //player callbacks
    lv_obj_add_event_cb(objects.player_record_button, player_record_changed, LV_EVENT_VALUE_CHANGED, NULL);

    //tuner callbacks
    lv_obj_add_event_cb(objects.tuner_state, tuner_state, LV_EVENT_VALUE_CHANGED, NULL);

    transport.sendCommand(CmdListLoops{});
    transport.sendCommand(CmdListPedalboards{});
    transport.sendCommand(CmdSequencerListMidiFiles{});

    uint32_t sleep_ms;
    while (true)
    {
        uint32_t sleep_ms = lv_timer_handler();
        lv_sleep_ms(sleep_ms);
    }
}